import "./globals.css";
import "./fonts.css";
import { Web3Provider } from "../context/Provider";
import { ViewTransitions } from "next-view-transitions";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body
        className={`navigator-hand bg-[#5420ff] min-h-screen w-full h-full antialiased`}
      >
        <Web3Provider>
          {/* <Navbar /> */}
        {children}
        </Web3Provider>
      </body>
    </html>
    </ViewTransitions>
  );
}
