import "./globals.css";
import "./fonts.css";
import { Web3Provider } from "../context/Provider";
import { ViewTransitions } from "next-view-transitions";
import Nav from "@/components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body
        className={`navigator-hand bg-[#FFE6CD] min-h-screen antialiased`}
      >
        <Web3Provider>
          <Nav />
        {children}
        </Web3Provider>
      </body>
    </html>
    </ViewTransitions>
  );
}
