import "./globals.css";
import "./fonts.css";
import { Web3Provider } from "../context/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`navigator-hand antialiased`}
      >
        <Web3Provider>
        {children}
        </Web3Provider>
      </body>
    </html>
  );
}
