import Bar from "@/components/home/Bar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`navigator-hand bg-[#5420ff] min-h-screen w-full h-full antialiased`}
      >
          <Bar />
        {children}
      </body>
    </html>
  );
}
export default Layout;
