import Bar from "@/components/home/Bar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout({
  children,
}) {
  return (
      <div
        className={`navigator-hand bg-[#fff] min-h-screen w-full h-full antialiased`}
      >
          <Bar />
        <div className="w-full h-full pl-12">
        {children}
        </div>
      </div>
  );
}
export default Layout;
